### ISSUE TITLE
intermittent error loading after build

### ISSUE THREAD

**Issue by paulprogrammer** [AJStacy/adze#165] opened 2024-07-21 03:04 UTC
My project is a TS/JS hybrid Frankenstein built using vite with esbuild.  Vite uses rollup as the bundler.

After some changes to my web app using adze, I will see the following error in the console, which ends the load of my app:

```
index.js:12 Uncaught TypeError: Object.defineProperty called on non-object
    at Function.defineProperty (<anonymous>)
    at index.js:12:8
    at zl (index.js:14:41)
    at qa (BaseLog.js:21:15)
    at index.js:13:14
    at Kl (index.js:15:46)
    at T_ (bundle.js:6:13)
    at index.js:13:14
    at gt (index.js:19:40)
    at filters.js:4:14
```

The files listed here are all in the adze package.

After a few changes to my JS, sometimes the error just goes away, until a few changes later.

My spidey senses tell me that this has something to do with timing of loading an object vs using an object.  To attempt to fix this, I have walled off the configuration of my adze in a TS module, with the hope that using a single point of entry would help.  The error stack trace below has, as far as I can tell, never been called.

```javascript
// logger.ts
import { adze, createShed } from 'adze';

createShed({
    globalCfg: {
        logLevel: 9, // TODO: environment based config
        useEmoji: true
    }
});

// gratuitous use of await/async as a lame way of doing memoization
// and to ensure the seal() is called before the logger can be used.
const logger = await (async function () {
    // I used to have the shed creation here, but it doesn't seem to matter.
    try {
        return adze().seal();
    } catch (e) {
        console.log((<Error>e).stack);
        return function () { // make typescript happy
            return {
                verbose: console.log,
                debug: console.log,
                info: console.log,
                error: console.log
            }
        }
    }
})()

export default logger;
```

```javascript
// various-app-files.ts
import logger from './logger'

// do stuff
logger().verbose("hello world");
// more stuff
```

I am not a JS guru, and really don't know what the next step is to debug this issue.

I'm thinking it might be a bundler issue, or some kind of order of execution issue?

**Comment by paulprogrammer** [comment] 2024-07-21 04:08
Terser seems to deal with adze actually.  It's a bit slower though.

**Comment by paulprogrammer** [comment] 2024-07-25 19:53
Terser sometimes has the same issue.

**Comment by AJStacy** [comment] 2024-07-29 18:25
Hi Paul,

So, this is likely a bundling issue. As far as your code for using Adze, everything looks fine. I can really only guess at what the problem is specifically without seeing more details, but my hunch is that it has to do with how your targeting the output of your es modules. I know that's not super helpful, but it would be difficult to diagnose without seeing all of the configuration of your codebase.

As a side note, this line: `return adze().seal();` isn't actually necessary because you aren't sealing any special configuration into your logger. You really only need to call `seal()` if you want to apply a global modifier like `.timestamp` or something like that. Otherwise your Shed configuration will always take precedence throughout your app. You can pretty much skip all of your code after your `createShed` declaration.

Sorry I couldn't be of more help with your build issue.

P.S. - Adze v2 should be released in the near future which will be much more modern. Keep your eye out for it 😄

**Comment by AJStacy** [comment] 2024-07-31 20:44
I'm going to close this for now, but please open up another ticket if it turns out the issue is related to Adze.

**Closed by AJStacy** 2024-07-31 20:44 UTC

**Comment by paulprogrammer** [comment] 2024-07-31 21:09
The build is a pretty vanilla vite build using esbuild or terser (depending on which one is causing me problems with adze today), and an es2022 target.  I could probably change the target, I just don't understand what the tradeoffs are, so are just hoping for something that mostly works.
